### ISSUE TITLE
KallistiOS build system needs an overhaul

### ISSUE THREAD

**Issue by GravisZro** [KallistiOS/KallistiOS#3]
I recently wanted to set up a toolchain for DC and stumbled across KallistiOS.  I'm not trying to be mean but the setup you have for building KOS is a disaster and I honestly want to help fix it.

Steps to fixing:
- Move everything that isn't part of library into another repo for building an SDK, [like this.](https://github.com/GravisZro/dreamcast-sdk)
- Install toolchains to /usr like it's intended to be! (solves 99% of your build environment issues)
- Consolidate all your makefiles for KOS into a single makefile.
- Eliminate all the environmental setup shell scripts.  All the vars belong in the makefile.

I'm in the progress of replacing the "dc-chain" utilities with a single easy to use POSIX script.  I realize I'm reinventing the wheel here but the existing system is [too clever by half](https://en.wiktionary.org/wiki/too_clever_by_half).  If anything is moved then it breaks.

If you wish to contact me, I'm Gravis on Freenode and EFNet.

**Comment by ljsebald** [comment]
Before you go reinventing the wheel, I'd like to point out a couple of things...

1. /usr is traditionally reserved for system-installed packages. It would not be proper to install our tools there directly. /usr/local is fine, and what many people have used in the past. /opt/toolchains was chosen as the default for a number of reasons. /opt is often world-writable, for one (thus you don't necessarily need superuser privileges to install or update things) and other [well known](http://devkitpro.org) console development toolchains do things similarly.

2. Eliminating all the env vars will pretty much break compilation of everyone's projects if they don't follow the exact same scheme you do. As it is, this isn't a problem. I often switch back and forth between machines where the toolchain is installed in /usr/local (my older box) and in /opt/toolchains and I don't have any problems because of the envvar setup that we have. The setup works and has been stable for over a decade.

3. There are many other "single shell script" solutions to building a full toolchain like the one over [here](http://dcemulation.org/?title=Compiling_KOS_on_Linux), and there have been many more over the years that have been around too (I wrote one myself way back in the day for use on a Windows 98 box running MinGW/MSYS).

I wouldn't argue that we are too clever by half when we have a system that has been stable and kept things working for over a decade across many different platforms with relative ease and without major changes. Sure, our documentation included with things is probably really bad (and we've largely lacked an "official" installation guide that would have been useful), but there are [lots of resources](http://dcemulation.org/phpBB/viewforum.php?f=29) available to help people out (and an IRC channel on freenode too (#dreamcastdev), of course).

I'm not trying to discourage you from trying to attack a problem that you might see, but rather I'm just stating that I don't see it as a problem personally.

**Comment by SeleDreams** [comment]
wouldn't cmake be a more convenient system overall ?

**Comment by gyrovorbis** [comment]
I'm a CMake user with KOS, as are many of us... at the application layer. 

I had thought about PR-ing the toolchain file we're using to build and use KOS so that you can use CMake externally with your projects... I'm not so sure that I agree we need to change the whole build system away from Make which has been fine for me since I started here when I was literally 13, but if it's more modern stuff like CMake support, just know that can be a single toolchain file added to the repo that you build with.

**Comment by SeleDreams** [comment]
I think the whole setup process can be made easier by simply having official docker images available on dockerhub so yeah it's not required to change the build system of the entire KOS source, but just having some cmake modules easy to use integrated at the same time as a docker would be great

**Comment by SeleDreams** [comment]
![Capture d’écran du 2023-01-31 21-28-21](https://user-images.githubusercontent.com/16335601/215875339-101694f2-dd05-4fc9-bbbd-9832d571220d.png)
there is one that I currently use with minor modifications that does the trick however, i think it is rarely updated so it's probably outdated, and since it doesn't have cmake modules bundled from what i know i'll need to make my own (unless there are ones under permissive licences out there)
