### ISSUE TITLE
Binutils patch needed to replace utils/ldscripts/shlelf.xc

### ISSUE THREAD

**Issue by GravisZro** [KallistiOS/KallistiOS#4]
So I finally tracked down that `utils/ldscripts/shlelf.xc` is used for everything.  However, it contains an absolute path which isn't correct.  In searching for the origin of ldscripts from binutils (binutils-x.xx/ld/emulparams), I found this would be an excellent opportunity to add "dreamcast" or something as a target by making a linker template script.  If nothing else, this linker script should at least be copied over the shlefl.xc after binutils generates it for the toolchain.

**Comment by ljsebald** [comment]
Yes, that linker script is pretty much used for everything, as you've deduced.

The path that's in the linker script would only add that to the list of locations for standard libraries that is already built-in to the toolchain. That line probably should indeed be removed, but it doesn't actually seem to have to be replaced by anything (it doesn't match my installation and I can still link things properly).

There used to be a patchset for binutils/newlib/gcc that added a sh-sega-dreamcast target back in the day. The problem with that approach is that it tends to break anything else you might install that has GNU-style configure scripts (those things would also have to be patched to add that unknown target in). Also, someone would have to maintain those patchsets, which is something that nobody seemed to be interested in doing. Thus, we've pretty much just used the normal sh-elf target and solved the problem with various linker flags (and more recently with that linker script). Heck, the linker script's only in there because the default linker script creates a .stack segment at a really inconvenient address for the Dreamcast (it was at a very low address) and considering that .start is at 0x8c01000 for Dreamcast stuff, thus meaning that we had to strip that segment out at link time or when creating raw binaries with objcopy to avoid having 2GB+ binaries being spat out at us...

**Comment by GravisZro** [comment]
What about just using a [gcc spec file](https://gcc.gnu.org/onlinedocs/gcc/Spec-Files.html)?

**Comment by ljsebald** [comment]
I'm not entirely sure I follow exactly what you're suggesting a spec file should be used for? I mean, sure, a spec file could be used for some stuff, but you'd still need to specify that spec file for calls to sh-elf-gcc.

**Comment by GravisZro** [comment]
spec files can really do anything but more importantly, they can be invoked from via command line switches.  This is [how a zillion different AVR devices are supported](https://gcc.gnu.org/gcc-5/changes.html#avr).  If you make a spec file for Dreamcast, it will be possible to have it included with the main distribution (no maintenance required!) and simply use `sh-elf-gcc -mdreamcast` to target the dreamcast.

**Comment by GravisZro** [comment]
Oh well crap, it looks like AVR added that by modifying the GCC config system.  That said, it's entirely possible to do with a patch.  In all cases, it's better to have a single spec file than a boatload of flags scattered around different scripts and makefiles.

**Comment by GravisZro** [comment]
I found it!  You can set the default specs [at the configure stage using --with-specs](https://gcc.gnu.org/install/configure.html).  I'm not 100% on this but I think the specs files could enable the use of other utilities through the use of extension filtering.  This would enable you to simply include your image files in the command line and have them automatically converted into a usable format.
